name = "HealthSampleData"
uuid = "b8464e9a-ae38-46a4-977b-86f00930f698"
authors = ["Jacob Zelko <jacobszelko@gmail.com>"]
version = "0.0.1"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"

[compat]
DataDeps = "0.7"
julia = "1"
